config/routes.rb
Rails.application.routes.draw do
  #get 'home/zipcode'
  root 'home#index'

  post "zipcode" => 'home#zipcode'
  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	

  def index
  	require 'net/http'
  	require 'json'
  	require 'openssl'
 
  	@url = 'http://api.openweathermap.org/data/2.5/weather?zip=77080,us&units=imperial&APPID=7213276d8be9af9fb6bec1576093ea7a'
  	@uri = URI(@url)

  	http = Net::HTTP.new(@uri.host, @uri.port)
  	http.use_ssl = true
  	http.verify_mode = OpenSSL::SSL::VERIFY_NONE

  	@response = Net::HTTP.get(@uri)
  	@output = JSON.parse(@response)

  	if @output["cod"] == "404"
  		@color_output = "Error"
  		@final_output = "Error, please check your Zipcode!"
  	else
  		@color_output = Float(@output["main"]["temp"])
  		@final_output = "#{@output["main"]["temp"]}  degrees Fahrenheit, is the current temperature in your neighborhood (Zipcode: 77080)."
  	end 

  	if @color_output == "Error"
  		@api_color = "grey"
    elsif @color_output >= 90.0  
  		@api_color = "red"
  	
   	elsif @color_output < 90.0 && @color_output >= 65.0 
  		@api_color = "orange"

  	elsif @color_output < 65.0 && @color_output >= 32.0 
  		@api_color = "blue"

  	elsif @color_output < 32.0
  		@api_color = "lightblue"
  
  	end

  end

  def zipcode
    @zip_query = params[:zipcode]
    if params[:zipcode] == ""
      @final_output = "Error, Zipcode was not entered!"
    
    elsif params[:zipcode]
      require 'net/http'
      require 'json'
      require 'openssl'
   
      @url = 'http://api.openweathermap.org/data/2.5/weather?zip=' + @zip_query + ',us&units=imperial&APPID=7213276d8be9af9fb6bec1576093ea7a'
      @uri = URI(@url)

      http = Net::HTTP.new(@uri.host, @uri.port)
      http.use_ssl = true
      http.verify_mode = OpenSSL::SSL::VERIFY_NONE

      @response = Net::HTTP.get(@uri)
      @output = JSON.parse(@response)

      if @output["cod"] == "404"
        @color_output = "Error"
        @final_output = "Error, please check your Zipcode!"
      else
        @color_output = Float(@output["main"]["temp"])
        @final_output = "#{@output["main"]["temp"]}  degrees Fahrenheit, is the current temperature in your neighborhood (Zipcode: #{@zip_query})."
      end 

      if @color_output == "Error"
        @api_color = "grey"
      elsif @color_output >= 90.0  
        @api_color = "red"
      
      elsif @color_output < 90.0 && @color_output >= 65.0 
        @api_color = "orange"

      elsif @color_output < 65.0 && @color_output >= 32.0 
        @api_color = "blue"

      elsif @color_output < 32.0
        @api_color = "lightblue"
    
      end 
    end 
  end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <%= link_to "WaterFlask", root_path, class: "navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      
    </ul>
    <%= form_tag zipcode_path :method => 'POST' do %>
    <div class="form-inline my-2 my-lg-0">
      <%= text_field_tag 'zipcode', nil, placeholder: "Search Zipcode" , class: "form-control mr-sm-2" %>
      <%= submit_tag 'Search', class: "btn btn-outline-success my-2 my-sm-0" %>

    </div>
    <% end %>
  </div>
</nav>

app/views/home/index.html.erb
    <div class="container-home" style="display: grid; grid-template-rows: 5fr;">

		<div class="jumbotron <%= @api_color %>">
		  <h1 class="display-4">WaterFlask Application</h1>
		  <p class="lead"><b><%= @final_output %> </b></p>
		  <hr>

		</div>
	



	</div>

app/views/home/zipcode.html.erb
   <div class="container-home" style="display: grid; grid-template-rows: 5fr;">

		<div class="jumbotron <%= @api_color %>">
		  <h1 class="display-4">WaterFlask Application</h1>
		  <p class="lead"><b><%= @final_output %> </b></p>
		  <hr>

		</div>

	</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WaterFlask</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<%= render 'home/navbar' %>
  	<div class="container">
  		<br/>
  		<%= image_tag("logos/dehydration.jpg") %>
    	<%= yield %>
    	
    </div>




  </body>
</html>